### ISSUE TITLE
Can't set global export name ('name' option)

### ISSUE THREAD

**Issue by flawyte** [cmtt/gulp-webmake#2]
Hi,

I'm trying to pass options to webmake to set the exposed variable name but it doesn't work :

```javascript
gulp.task('build', ['clean'], function() {
    return gulp.src(['index.js'])
        .pipe(webmake({ name: 'SomeName' })) // Should expose module via 'window.SomeName' but doesn't
        .pipe(rename({ basename: 'some-name', extname: '.js' }))
        .pipe(gulp.dest('dist'))
        .pipe(uglify())
        .pipe(rename({ suffix: '.min' }))
        .pipe(gulp.dest('dist'))
    ;
});
```

What am I doing wrong ?

**Comment by flawyte** [comment]
It looks like the problem comes from webmake itself. See https://github.com/medikoo/modules-webmake/issues/50.

**Comment by cmtt** [comment]
@flawyte Thank you for filing the issue.
It seems so, but I will additionally have a closer look on what is going wrong here.

**Comment by cmtt** [comment]
@flawyte @medikoo has corrected this issue and this module was updated accordingly, too.
Thanks again!

**Comment by flawyte** [comment]
Thank you too :)
