### ISSUE TITLE
Upgrading to 0.0.3 breaks everything

### ISSUE THREAD

**Issue by raffomania** [cmtt/gulp-webmake#3]
When upgrading gulp-webmake to 0.0.3, something goes wrong along the build process. The compiled app file doesn't contain my code anymore, but instead contains something along the lines of 

```
eval("[object Object]\n//# sourceURL=mySourceMap.js");
```

Note I'm using a babel transform like this:

```
return gulp.src(paths.js.entryPoint)
    .pipe(plugins.webmake({
        sourceMap: true,
        transform: function(filename, code) {
            var transformed = babel.transform(code, { sourceMap: true });
            return {
                code: transformed.code,
                sourceMap: transformed.map
            };
        }
    }))
```

I'm not sure if this is a bug in the gulp plugin or in webmake itself.

**Comment by cmtt** [comment]
Hello, thank you for reporting this issue!

gulp-webmake is currently bound to modules-webmake 0.3.37 which doesn't fix your [modules-webmake Issue #51](https://github.com/medikoo/modules-webmake/issues/51).

I will update this module accordingly later this day.

In the meanwhile, I recommend to install the current version 0.3.39 of modules-webmake manually in gulp-webmake's directory (don't forget to update package.json of gulp-webmake beforehand).

If this doesn't resolve your problem, please let me know.

**Comment by cmtt** [comment]
@raffomania, this module was updated to use webmake 0.3.39.

**Comment by raffomania** [comment]
Thanks a lot!
